[package]
name = "wide-log"
version = "0.1.0"
authors = ["David Grantham"]
edition = "2024"
description = "A fast wide event logging crate a la loggingsucks.com"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/dhuseby/wide-log"

[dependencies]
faststr = "0"
serde = { version = "1", features = ["derive"] }
smallvec = { version = "1", features = ["union", "write", "serde"] }
sonic-rs = "0"
thiserror = "2"
tracing = "0"
wide-log-macros = { path = "wide-log-macros" }

# optional
tokio = { version = "1", features = ["rt"], optional = true }
tower = { version = "0", optional = true }

[features]
default = []
tokio = ["dep:tokio", "dep:tower", "wide-log-macros/tokio"]

[dev-dependencies]
criterion = { version = "0", features = ["html_reports"] }
tracing-subscriber = { version = "0", features = ["env-filter"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync", "net"] }
axum = { version = "0", default-features = false, features = ["http1", "tokio"] }

[[bench]]
name = "comparison"
harness = false

[[test]]
name = "async"
required-features = ["tokio"]

[[example]]
name = "async_single_thread"
required-features = ["tokio"]

[[example]]
name = "async_multi_thread"
required-features = ["tokio"]

[[example]]
name = "axum_ok"
required-features = ["tokio"]
