[package]
name = "wide-log-macros"
version = "0.4.1"
authors = ["David Grantham"]
edition = "2024"
description = "Macros for a fast wide event logging crate a la loggingsucks.com"
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/dhuseby/wide-log"

[lib]
proc-macro = true

[features]
tokio = []
uuid = []

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
