//! Tower middleware support for wide-log.
//!
//! The `WideLogLayer` middleware is generated by the [`wide_log!`](crate::wide_log!)
//! macro alongside the other generated items. It wraps every incoming request
//! in a `scope_default()` call, creating a wide-log guard and task-local storage
//! automatically — no manual `scope_default()` or `EventKeyGuard::new()` needed
//! in handler code.
//!
//! Usage with axum:
//! ```rust,ignore
//! let app = Router::new()
//!     .route("/ok", get(ok))
//!     .layer(WideLogLayer);
//! ```
//!
//! The generated `WideLogLayer` implements `tower::Layer`, and
//! `WideLogMiddleware` implements `tower::Service`. Each call to the service
//! wraps the response future in `scope_default()`, so the guard is created
//! when the request starts and dropped (emitting the event JSON) when the
//! handler completes.