//! Tower middleware support for wide-log.
//!
//! **Feature gate:** `tokio`.
//!
//! The `WideLogLayer` middleware is generated by the [`wide_log!`](crate::wide_log!)
//! macro alongside the other generated items. It wraps every incoming request
//! in a `scope_default()` call, creating a wide-log guard and task-local storage
//! automatically — no manual `scope_default()` or `EventKeyGuard::new()` needed
//! in handler code.
//!
//! ## Usage with axum
//!
//! ```rust,ignore
//! let app = Router::new()
//!     .route("/ok", get(ok))
//!     .layer(WideLogLayer);
//! ```
//!
//! ## Why middleware, not `EventKeyGuard::new()`
//!
//! `tokio::task_local!` has no imperative setter — you can only set a
//! task-local value by wrapping a future with `.scope(value, future)`. The
//! middleware provides that wrapper automatically. `EventKeyGuard::new()`
//! (the sync API) sets `thread_local!`, which is stale if a multi-threaded
//! runtime moves the task to another thread.
//!
//! ## No special setup in nested calls
//!
//! Any `info!()`, `warn!()`, `wl_set!`, etc. call — whether in the handler
//! directly, in a called sync function, or in a called async function — finds
//! the event via `current()`, which checks task-local first. No arguments or
//! threading needed.
//!
//! ## Generated types
//!
//! - `WideLogLayer` — implements `tower::Layer`; `Clone`
//! - `WideLogMiddleware<S>` — implements `tower::Service`; `Clone` when `S: Clone`
//! - `WideLogFuture<ResBody, Err>` — the response future, wraps the inner
//!   future in `scope_default()`
