//! Non-blocking stdout emit for wide events.
//!
//! The default `default_emit` function (generated by [`wide_log!`](crate::wide_log))
//! hands the serialized JSON bytes to this module, which forwards them to a
//! dedicated writer thread. The writer owns a `BufWriter<Stdout>` and flushes
//! after every message so logs land promptly without blocking the calling
//! thread.
//!
//! [`submit`] never blocks: it sends the `Vec<u8>` over an unbounded
//! `std::sync::mpsc` channel to the writer thread. If the channel is closed
//! (e.g. the writer thread has exited during process teardown), the payload
//! is dropped silently and an atomic counter is incremented; the count is
//! exposed via [`dropped_events`].
//!
//! Because the channel `Sender` lives in a process-global `OnceLock`, it is
//! never dropped on normal process exit — the writer thread would be killed
//! by the runtime before draining its buffer. Call [`flush`] at program exit
//! (e.g. at the end of `main`) to block until all pending events have been
//! written and the `BufWriter` flushed. (Forced termination such as `SIGKILL`
//! will still lose any bytes buffered in the writer thread.)
//!
//! ## Phase 2: `Vec<u8>` pipeline
//!
//! The producer's `Vec<u8>` is sent over the channel directly — no
//! `String` conversion, no `from_utf8_unchecked`, no `Vec::split_off(0)`
//! copy. The writer thread receives the bytes verbatim and writes them
//! to the `BufWriter`. A trailing `'\n'` is appended by the producer
//! (in `default_emit`) so the writer's hot path is just a `write_all`.
//!
//! ## Phase 2: two-buffer ping-pong (placeholder)
//!
//! The full two-buffer ping-pong optimization (where the writer keeps a
//! spare `Vec<u8>` and hands it back to the producer via a return
//! channel) is deferred to `0.7.0` per the implementation plan. In
//! `0.6.0` the producer's `EMIT_BUF` thread-local is the only
//! long-lived `Vec<u8>`; the writer drops each `Vec<u8>` it receives
//! after `write_all`. This is correct, but allocates on the
//! writer side for every event.
//!
//! [`submit`]: submit
//! [`dropped_events`]: dropped_events
//! [`flush`]: flush

use std::io::Write;
use std::sync::OnceLock;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::mpsc::{self, Sender};

static DROPPED: AtomicU64 = AtomicU64::new(0);
static SENDER: OnceLock<Sender<Job>> = OnceLock::new();

enum Job {
    /// A serialized wide-event line, including the trailing `'\n'`. The
    /// producer's `Vec<u8>` is moved over the channel without copy.
    Line(Vec<u8>),
    /// An ack-channel that the writer signals when the buffer has been
    /// flushed. Used by [`flush`].
    Flush(mpsc::SyncSender<()>),
}

/// Number of events dropped because the writer thread's channel was closed.
///
/// Incremented on a best-effort basis whenever [`submit`] fails to enqueue a
/// payload. Read this for optional metrics; a non-zero value typically
/// indicates the writer thread has exited (e.g. during process teardown).
pub fn dropped_events() -> u64 {
    DROPPED.load(Ordering::Relaxed)
}

/// Enqueue a serialized wide-event JSON line for the writer thread.
///
/// The `Vec<u8>` is sent over an unbounded channel to a single dedicated
/// writer thread that owns a `BufWriter<Stdout>`. This function never
/// blocks on I/O: if the channel is closed, the payload is dropped
/// silently and [`dropped_events`] is incremented.
///
/// The writer thread is started lazily on the first call.
///
/// Call [`flush`] at program exit to guarantee all pending lines are
/// written before the process terminates.
pub fn submit(bytes: Vec<u8>) {
    let sender = SENDER.get_or_init(init_sender);
    if sender.send(Job::Line(bytes)).is_err() {
        DROPPED.fetch_add(1, Ordering::Relaxed);
    }
}

/// Block until all previously-submitted events have been written and the
/// writer's `BufWriter` has been flushed.
///
/// Call this at program exit (e.g. at the end of `main`) to guarantee no
/// pending events are lost when the process terminates. The `OnceLock`-held
/// `Sender` is never dropped on normal exit, so without an explicit `flush`
/// the writer thread would be killed by the runtime before draining its
/// buffer.
///
/// This function may block briefly while the writer thread drains. It is
/// safe to call multiple times.
pub fn flush() {
    let sender = match SENDER.get() {
        Some(s) => s,
        None => return,
    };
    let (ack_tx, ack_rx) = mpsc::sync_channel(0);
    if sender.send(Job::Flush(ack_tx)).is_err() {
        return;
    }
    let _ = ack_rx.recv();
}

fn init_sender() -> Sender<Job> {
    let (tx, rx) = mpsc::channel::<Job>();

    let _ = std::thread::Builder::new()
        .name("wide-log-stdout".into())
        .spawn(move || writer_loop(rx));

    tx
}

fn writer_loop(rx: mpsc::Receiver<Job>) {
    let stdout = std::io::stdout();
    let mut buf = std::io::BufWriter::new(stdout);

    for job in rx {
        match job {
            Job::Line(bytes) => {
                // `write_all` to a `BufWriter` only fails in exceptional cases
                // (e.g. broken pipe). On error we drop the line and continue;
                // the dropped-events counter is reserved for send-side
                // failures, but a broken pipe here is similarly unrecoverable.
                //
                // Phase 2 §2.3: a future return-slot protocol could
                // hand this `Vec<u8>` back to the producer (post-`0.6.0`,
                // tracked for `0.7.0`). For now the `Vec` is dropped here
                // and the producer reuses its own `EMIT_BUF` thread-local.
                if buf.write_all(&bytes).is_err() {
                    continue;
                }
                let _ = buf.flush();
            }
            Job::Flush(ack) => {
                let _ = buf.flush();
                let _ = ack.send(());
            }
        }
    }

    // If the loop ever ends (all senders dropped — not the normal path,
    // since the sender lives in a `OnceLock`), flush any remaining bytes.
    let _ = buf.flush();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dropped_events_starts_at_zero() {
        // Other tests in the same process may call submit(), so only assert
        // the counter is loadable and non-decreasing; do not assume a specific
        // value. This test exists mainly to exercise the load path.
        let _ = dropped_events();
    }

    #[test]
    fn submit_accepts_bytes() {
        // The writer thread is shared process-wide; we can't easily assert
        // that this exact payload was written. Just ensure submit() does not
        // panic for a typical input.
        let mut bytes = b"{\"hello\":true}".to_vec();
        bytes.push(b'\n');
        submit(bytes);
    }

    #[test]
    fn dropped_counter_is_exposed() {
        // The counter is a u64; loading it should never panic.
        let _ = dropped_events();
    }

    #[test]
    fn flush_is_callable_and_drains() {
        // Submit a line, then flush. flush() should return once the writer
        // has processed the line. If this hangs, the writer thread is dead.
        let mut bytes = b"{\"flush_test\":true}".to_vec();
        bytes.push(b'\n');
        submit(bytes);
        flush();
    }

    // ── Phase 2: Vec<u8> pipeline tests ──

    #[test]
    fn submit_accepts_owned_vec_without_copy() {
        // Verify that the new `Vec<u8>` interface works and that the
        // submission is a non-blocking channel send. We can't easily
        // assert that no copy happened, but we can verify that an
        // empty `Vec` and a `Vec` of any size are accepted.
        submit(Vec::new());
        submit(vec![0u8; 0]);
        submit(vec![b'a'; 1024]);
        submit(vec![b'Z'; 65_536]);
    }

    #[test]
    fn submit_does_not_block_under_load() {
        // Submit a burst of events and verify that submit() returns
        // promptly (channel send is non-blocking for an unbounded
        // channel). The writer thread drains in the background.
        for i in 0..1000 {
            let mut bytes = format!("{{\"i\":{i}}}\n").into_bytes();
            bytes.push(b'\n');
            submit(bytes);
        }
        // Flush forces a drain; this must return without panic.
        flush();
    }

    #[test]
    fn dropped_counter_increments_on_closed_channel() {
        // We can't easily close the channel from a test (the writer
        // thread is a daemon), so just verify the counter is readable
        // and the type is `u64`. Real dropped-counting behavior is
        // exercised by the higher-level integration tests.
        let before = dropped_events();
        let _ = before;
    }

    // The full end-to-end behavior (default_emit writing a single bare JSON
    // line to stdout with no tracing envelope) is exercised by the subprocess
    // stdout-capture test in tests/stdout_emit.rs.
}
